---
services:
  db2:
    image: docker.io/ibmcom/db2:11.5.0.0
    container_name: db2
    environment:
      LICENSE: accept
      DB2INST1_PASSWORD: passw0rd
      DBNAME: db2
      AUTOCONFIG: "true"
    ports:
      - "55000:55000"

  openliberty_app:
    image: docker.io/open-liberty:kernel-slim-java17-openj9
    container_name: openliberty_app
    ports:
      - "9080:9080"
      - "9443:9443"
    environment:
      DB2_URL: jdbc:db2://db2:50000/db2
      DB2_USER: db2inst1
      DB2_PASSWORD: passw0rd

