services:
  db2:
    image: ibmcom/db2:11.5.0.0
    container_name: db2
    environment:
      LICENSE: accept
      DB2INST1_PASSWORD: passw0rd
      DBNAME: db2
      AUTOCONFIG: "true"
    ports:
      - "50000:50000"
    volumes:
      - ./db2/resources/db2:/opt/ibm/db2/V11.5/java/
      - ./db2/dll/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    image: redhat/ubi9
    container_name: app
    ports:
      - "9080:9080"
    volumes:
      - ./MW/WAS/:/WAS/
      - ./MW/logs:/MW/logs
      - ./db2/resources/db2:/MW/WAS/wlp/usr/share/resources/db2
      - ./MW/IIM/configuration/:/opt/IBM/InstallationManager/eclipse/configuration/
    environment:
      DB2_URL: jdbc:db2://db2:50000/db2
      DB2_USER: db2inst1
      DB2_PASSWORD: passw0rd
