---
- name: Setup IBM Installation Manager and WebSphere Liberty
  hosts: all
  become: yes
  vars:
    iso_path: /iso/rhel-9.4-x86_64-boot.iso
    iim_zip: /MW/IIM/agent.installer.linux.gtk.x86_64_1.9.2008.20240227_0018.zip
    iim_config_dir: /MW/IIM/configuration
    iim_install_dir: /opt/IBM/InstallationManager
    iim_log: /MW/logs/01.IIM_install.log
    was_zip: /MW/WAS/wlp-webProfile8-java8-linux-x86_64-24.0.0.6.zip

  tasks:
    - name: Install required packages
      package:
        name: unzip
        state: present

    - name: Create required directories
      file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - /iso
        - /MW/IIM/configuration
        - /MW/WAS
        - /MW/logs

    - name: Copy RHEL ISO
      copy:
        src: iso/rhel-9.4-x86_64-boot.iso
        dest: "{{ iso_path }}"
        mode: "0644"

    - name: Copy IIM zip
      copy:
        src: MW/IIM/agent.installer.linux.gtk.x86_64_1.9.2008.20240227_0018.zip
        dest: "{{ iim_zip }}"
        mode: "0644"

    - name: Copy IIM configuration directory
      copy:
        src: MW/IIM/configuration/
        dest: "{{ iim_config_dir }}/"
        mode: "0755"
      notify: Validate IIM config

    - name: Unzip IIM installer
      unarchive:
        src: "{{ iim_zip }}"
        dest: /MW/IIM
        remote_src: yes

    - name: Run IIM install
      command: >
        /MW/IIM/installc
        -acceptLicense
        -installationDirectory {{ iim_install_dir }}
        -log {{ iim_log }}
        -dataLocation {{ iim_config_dir }}
      args:
        creates: "{{ iim_install_dir }}/tools/imcl"

    - name: Copy WebSphere Liberty zip
      copy:
        src: MW/WAS/wlp-webProfile8-java8-linux-x86_64-24.0.0.6.zip
        dest: "{{ was_zip }}"
        mode: "0644"

    - name: Unzip WebSphere Liberty
      unarchive:
        src: "{{ was_zip }}"
        dest: /MW/WAS
        remote_src: yes

  handlers:
    - name: Validate IIM config
      debug:
        msg: "IIM configuration directory copied successfully."
